/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PhiiPayrollInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "SECONDS_IN_MONTH"
      | "calculateAccrued"
      | "employees"
      | "fund"
      | "owner"
      | "paused"
      | "paymentToken"
      | "registerEmployee"
      | "renounceOwnership"
      | "requestAdvance"
      | "settleSalary"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdvanceWithdrawn"
      | "EmployeeRegistered"
      | "OwnershipTransferred"
      | "Paused"
      | "SalaryDeposited"
      | "SalarySettled"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "SECONDS_IN_MONTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateAccrued",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "employees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "fund", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerEmployee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestAdvance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleSalary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "SECONDS_IN_MONTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateAccrued",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "employees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAdvance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AdvanceWithdrawnEvent {
  export type InputTuple = [employee: AddressLike, amount: BigNumberish];
  export type OutputTuple = [employee: string, amount: bigint];
  export interface OutputObject {
    employee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeRegisteredEvent {
  export type InputTuple = [employee: AddressLike, salary: BigNumberish];
  export type OutputTuple = [employee: string, salary: bigint];
  export interface OutputObject {
    employee: string;
    salary: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryDepositedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalarySettledEvent {
  export type InputTuple = [employee: AddressLike, amount: BigNumberish];
  export type OutputTuple = [employee: string, amount: bigint];
  export interface OutputObject {
    employee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PhiiPayroll extends BaseContract {
  connect(runner?: ContractRunner | null): PhiiPayroll;
  waitForDeployment(): Promise<this>;

  interface: PhiiPayrollInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  SECONDS_IN_MONTH: TypedContractMethod<[], [bigint], "view">;

  calculateAccrued: TypedContractMethod<
    [_employee: AddressLike],
    [bigint],
    "view"
  >;

  employees: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean, boolean] & {
        monthlySalary: bigint;
        lastPayTimestamp: bigint;
        withdrawnThisPeriod: bigint;
        isActive: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  fund: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  registerEmployee: TypedContractMethod<
    [_employee: AddressLike, _monthlySalary: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestAdvance: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleSalary: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "SECONDS_IN_MONTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateAccrued"
  ): TypedContractMethod<[_employee: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "employees"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean, boolean] & {
        monthlySalary: bigint;
        lastPayTimestamp: bigint;
        withdrawnThisPeriod: bigint;
        isActive: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerEmployee"
  ): TypedContractMethod<
    [_employee: AddressLike, _monthlySalary: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestAdvance"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleSalary"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AdvanceWithdrawn"
  ): TypedContractEvent<
    AdvanceWithdrawnEvent.InputTuple,
    AdvanceWithdrawnEvent.OutputTuple,
    AdvanceWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeRegistered"
  ): TypedContractEvent<
    EmployeeRegisteredEvent.InputTuple,
    EmployeeRegisteredEvent.OutputTuple,
    EmployeeRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "SalaryDeposited"
  ): TypedContractEvent<
    SalaryDepositedEvent.InputTuple,
    SalaryDepositedEvent.OutputTuple,
    SalaryDepositedEvent.OutputObject
  >;
  getEvent(
    key: "SalarySettled"
  ): TypedContractEvent<
    SalarySettledEvent.InputTuple,
    SalarySettledEvent.OutputTuple,
    SalarySettledEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AdvanceWithdrawn(address,uint256)": TypedContractEvent<
      AdvanceWithdrawnEvent.InputTuple,
      AdvanceWithdrawnEvent.OutputTuple,
      AdvanceWithdrawnEvent.OutputObject
    >;
    AdvanceWithdrawn: TypedContractEvent<
      AdvanceWithdrawnEvent.InputTuple,
      AdvanceWithdrawnEvent.OutputTuple,
      AdvanceWithdrawnEvent.OutputObject
    >;

    "EmployeeRegistered(address,uint256)": TypedContractEvent<
      EmployeeRegisteredEvent.InputTuple,
      EmployeeRegisteredEvent.OutputTuple,
      EmployeeRegisteredEvent.OutputObject
    >;
    EmployeeRegistered: TypedContractEvent<
      EmployeeRegisteredEvent.InputTuple,
      EmployeeRegisteredEvent.OutputTuple,
      EmployeeRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "SalaryDeposited(uint256)": TypedContractEvent<
      SalaryDepositedEvent.InputTuple,
      SalaryDepositedEvent.OutputTuple,
      SalaryDepositedEvent.OutputObject
    >;
    SalaryDeposited: TypedContractEvent<
      SalaryDepositedEvent.InputTuple,
      SalaryDepositedEvent.OutputTuple,
      SalaryDepositedEvent.OutputObject
    >;

    "SalarySettled(address,uint256)": TypedContractEvent<
      SalarySettledEvent.InputTuple,
      SalarySettledEvent.OutputTuple,
      SalarySettledEvent.OutputObject
    >;
    SalarySettled: TypedContractEvent<
      SalarySettledEvent.InputTuple,
      SalarySettledEvent.OutputTuple,
      SalarySettledEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
