/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PhiiCoin__factory } from "./PhiiCoin__factory";
export { PhiiPayroll__factory } from "./PhiiPayroll__factory";
